

package main

/////////////////////////////////////////////////////////////////
//Code generated by chidley https://github.com/gnewton/chidley //
/////////////////////////////////////////////////////////////////

import (
	"bufio"
	"compress/bzip2"
	"compress/gzip"
	"encoding/json"
	"encoding/xml"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"math"
	"strings"
)

const (
	JsonOut = iota
	XmlOut
	CountAll
)

var toJson bool = false
var toXml bool = false
var oneLevelDown bool = false
var countAll bool = false
var musage bool = false

var uniqueFlags = []*bool{
	&toJson,
	&toXml,
	&countAll}

var filenames = [1]string{"/home/nakano/error_stderr.xml"}



func init() {

	flag.BoolVar(&toJson, "j", toJson, "Convert to JSON")
	flag.BoolVar(&toXml, "x", toXml, "Convert to XML")
	flag.BoolVar(&countAll, "c", countAll, "Count each instance of XML tags")
	flag.BoolVar(&oneLevelDown, "s", oneLevelDown, "Stream XML by using XML elements one down from the root tag. Good for huge XML files (see http://blog.davidsingleton.org/parsing-huge-xml-files-with-go/")
	flag.BoolVar(&musage, "h", musage, "Usage")
	//flag.StringVar(&filename, "f", filename, "XML file or URL to read in")

	flag.Int64Var(&recordLimit, "n", recordLimit, "Limit # records output")
}

var out int = -1

var counters map[string]*int

var recordLimit int64 = int64(math.MaxInt64)
var recordCounter = int64(0)

func main() {
	flag.Parse()

	if musage {
		flag.Usage()
		return
	}

	numSetBools, outFlag := numberOfBoolsSet(uniqueFlags)
	if numSetBools == 0 {
		flag.Usage()
                return
	}

	if numSetBools != 1 {
		flag.Usage()
		log.Fatal("Only one of ", uniqueFlags, " can be set at once")
	}

	counter := 0
	stop := false
	counters = make(map[string]*int)
	for i, _ := range filenames {
		filename := filenames[i]
		reader, xmlFile, err := genericReader(filename)
		if err != nil {
			log.Fatal(err)
			return
		}

		decoder := xml.NewDecoder(reader)

		for {
			if stop {
				break
			}
			token, _ := decoder.Token()
			if token == nil {
				break
			}
			switch se := token.(type) {
			case xml.StartElement:
				counter++
				handleFeed(se, decoder, outFlag)
				if recordCounter == recordLimit {
					stop = true
				}
			}

		}
		if stop {
			break
		}
		if xmlFile != nil {
			defer xmlFile.Close()
		}
	}
	if countAll {
		for k, v := range counters {
			fmt.Println(*v, k)
		}
	}
}

func handleFeed(se xml.StartElement, decoder *xml.Decoder, outFlag *bool) {
	if outFlag == &countAll {
		incrementCounter(se.Name.Space, se.Name.Local)
	} else {
                if !oneLevelDown{
        		if se.Name.Local == "Objs" && se.Name.Space == "http://schemas.microsoft.com/powershell/2004/04" {
	        	      var item Objs
			      decoder.DecodeElement(&item, &se)
			      switch outFlag {
			      case &toJson:
				      writeJson(item)
			      case &toXml:
				      writeXml(item)
			      }
		      }
                }else{
                   
        		if se.Name.Local == "Obj" && se.Name.Space == "http://schemas.microsoft.com/powershell/2004/04" {
			      recordCounter++
	        	      var item Obj
			      decoder.DecodeElement(&item, &se)
			      switch outFlag {
			      case &toJson:
				      writeJson(item)
			      case &toXml:
				      writeXml(item)
			      }
		      }
                   
        		if se.Name.Local == "S" && se.Name.Space == "http://schemas.microsoft.com/powershell/2004/04" {
			      recordCounter++
	        	      var item S
			      decoder.DecodeElement(&item, &se)
			      switch outFlag {
			      case &toJson:
				      writeJson(item)
			      case &toXml:
				      writeXml(item)
			      }
		      }
                   
               }
	}
}

func makeKey(space string, local string) string {
	if space == "" {
		space = "_"
	}
	return space + ":" + local
}

func incrementCounter(space string, local string) {
	key := makeKey(space, local)

	counter, ok := counters[key]
	if !ok {
		n := 1
		counters[key] = &n
	} else {
		newv := *counter + 1
		counters[key] = &newv
	}
}

func writeJson(item interface{}) {
	b, err := json.MarshalIndent(item, "", " ")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(b))
}

func writeXml(item interface{}) {
	output, err := xml.MarshalIndent(item, "  ", "    ")
	if err != nil {
		fmt.Printf("error: %v\n", err)
	}
	os.Stdout.Write(output)
}

func genericReader(filename string) (io.Reader, *os.File, error) {
	if filename == "" {
		return bufio.NewReader(os.Stdin), nil, nil
	}
	file, err := os.Open(filename)
	if err != nil {
		return nil, nil, err
	}
	if strings.HasSuffix(filename, "bz2") {
		return bufio.NewReader(bzip2.NewReader(bufio.NewReader(file))), file, err
	}

	if strings.HasSuffix(filename, "gz") {
		reader, err := gzip.NewReader(bufio.NewReader(file))
		if err != nil {
			return nil, nil, err
		}
		return bufio.NewReader(reader), file, err
	}
	return bufio.NewReader(file), file, err
}

func numberOfBoolsSet(a []*bool) (int, *bool) {
	var setBool *bool
	counter := 0
	for i := 0; i < len(a); i++ {
		if *a[i] {
			counter += 1
			setBool = a[i]
		}
	}
	return counter, setBool
}


///////////////////////////
/// structs
///////////////////////////

type AI struct {
	XMLName xml.Name `xml:"AI,omitempty" json:"AI,omitempty"`
	Flag bool `xml:",chardata" json:",omitempty"`
}

type AV struct {
	XMLName xml.Name `xml:"AV,omitempty" json:"AV,omitempty"`
	string string `xml:",chardata" json:",omitempty"`
}

type I64 struct {
	XMLName xml.Name `xml:"I64,omitempty" json:"I64,omitempty"`
	AttrN string`xml:"N,attr"  json:",omitempty"`
	Flag bool `xml:",chardata" json:",omitempty"`
}

type MS struct {
	XMLName xml.Name `xml:"MS,omitempty" json:"MS,omitempty"`
	I64 *I64 `xml:"http://schemas.microsoft.com/powershell/2004/04 I64,omitempty" json:"I64,omitempty"`
	PR *PR `xml:"http://schemas.microsoft.com/powershell/2004/04 PR,omitempty" json:"PR,omitempty"`
}

type Nil struct {
	XMLName xml.Name `xml:"Nil,omitempty" json:"Nil,omitempty"`
}

type Obj struct {
	XMLName xml.Name `xml:"Obj,omitempty" json:"Obj,omitempty"`
	AttrRefId string`xml:"RefId,attr"  json:",omitempty"`
	AttrS string`xml:"S,attr"  json:",omitempty"`
	MS *MS `xml:"http://schemas.microsoft.com/powershell/2004/04 MS,omitempty" json:"MS,omitempty"`
	TN *TN `xml:"http://schemas.microsoft.com/powershell/2004/04 TN,omitempty" json:"TN,omitempty"`
}

type Objs struct {
	XMLName xml.Name `xml:"Objs,omitempty" json:"Objs,omitempty"`
	AttrVersion string`xml:"Version,attr"  json:",omitempty"`
	Attrxmlns string`xml:"xmlns,attr"  json:",omitempty"`
	Obj *Obj `xml:"http://schemas.microsoft.com/powershell/2004/04 Obj,omitempty" json:"Obj,omitempty"`
	S []*S `xml:"http://schemas.microsoft.com/powershell/2004/04 S,omitempty" json:"S,omitempty"`
}

type PC struct {
	XMLName xml.Name `xml:"PC,omitempty" json:"PC,omitempty"`
	Number int8 `xml:",chardata" json:",omitempty"`
}

type PI struct {
	XMLName xml.Name `xml:"PI,omitempty" json:"PI,omitempty"`
	Number int8 `xml:",chardata" json:",omitempty"`
}

type PR struct {
	XMLName xml.Name `xml:"PR,omitempty" json:"PR,omitempty"`
	AttrN string`xml:"N,attr"  json:",omitempty"`
	AI *AI `xml:"http://schemas.microsoft.com/powershell/2004/04 AI,omitempty" json:"AI,omitempty"`
	AV *AV `xml:"http://schemas.microsoft.com/powershell/2004/04 AV,omitempty" json:"AV,omitempty"`
	Nil *Nil `xml:"http://schemas.microsoft.com/powershell/2004/04 Nil,omitempty" json:"Nil,omitempty"`
	PC *PC `xml:"http://schemas.microsoft.com/powershell/2004/04 PC,omitempty" json:"PC,omitempty"`
	PI *PI `xml:"http://schemas.microsoft.com/powershell/2004/04 PI,omitempty" json:"PI,omitempty"`
	SD *SD `xml:"http://schemas.microsoft.com/powershell/2004/04 SD,omitempty" json:"SD,omitempty"`
	SR *SR `xml:"http://schemas.microsoft.com/powershell/2004/04 SR,omitempty" json:"SR,omitempty"`
	T []*T `xml:"http://schemas.microsoft.com/powershell/2004/04 T,omitempty" json:"T,omitempty"`
}

type S struct {
	XMLName xml.Name `xml:"S,omitempty" json:"S,omitempty"`
	AttrS string`xml:"S,attr"  json:",omitempty"`
	string string `xml:",chardata" json:",omitempty"`
}

type SD struct {
	XMLName xml.Name `xml:"SD,omitempty" json:"SD,omitempty"`
}

type SR struct {
	XMLName xml.Name `xml:"SR,omitempty" json:"SR,omitempty"`
	Number int8 `xml:",chardata" json:",omitempty"`
}

type T struct {
	XMLName xml.Name `xml:"T,omitempty" json:"T,omitempty"`
	string string `xml:",chardata" json:",omitempty"`
}

type TN struct {
	XMLName xml.Name `xml:"TN,omitempty" json:"TN,omitempty"`
	AttrRefId string`xml:"RefId,attr"  json:",omitempty"`
	T []*T `xml:"http://schemas.microsoft.com/powershell/2004/04 T,omitempty" json:"T,omitempty"`
}


///////////////////////////

